### ISSUE TITLE
[20220313] Weekly AI ArXiv 만담 - 43회차 (1주년)

### ISSUE THREAD

**Issue by jungwoo-ha** [jungwoo-ha/WeeklyArxivTalk#43]
- Weekly AI Arxiv 1주년 경축 !!!! 모더레이터 분들 / 청취자 여러분들 모두 감사합니다!
- News
  - Deadlines
    - ECCV 2022: 서플 3.15 (모두들 수고하셨습니다)
    - Interspeech 2022: 3.21 (업데이트는 3.28까지)
  - [AI미래포럼 1주년 기념 새정부의 AI 국가전략 웨비나](https://www.youtube.com/channel/UCY8nyxAj5cU7ockuNodaS_g)
    - 관련기사: https://n.news.naver.com/article/015/0004673411
  - [모두가 AI를 원한다. 투자 봇물](https://news.naver.com/main/read.naver?mode=LSD&mid=sec&sid1=105&oid=028&aid=0002582573) 
- ArXiv
  - [DUAL: Textless Spoken Question Answering with Speech Discrete Unit Adaptive Learning](https://arxiv.org/abs/2203.04911) 
    - Meta 에서 공개한 Spoken QA를 위한 모델 + 데이터셋 NMSQA
    - NMSQA: SQuAD 1.1 을 Spoken QA 로 만든 것: spanning time 
    - DUAL: Pretrained LM (Longformer) + Spoken content encoder (HuBERT) --> Discrete latent representation (K-means)
    - Time을 index로 변환해서 맞추는 형태로 loss 정의
    - ASR + QA로 cascading 할 경우에 비해 error propagation에 대해 상당히 robust 
![image](https://user-images.githubusercontent.com/11782739/158052207-01bbace0-5161-430d-bf00-e91a89394aa9.png)
![image](https://user-images.githubusercontent.com/11782739/158052213-d00efbf5-4434-415e-90ab-603e359ee175.png)

  - [On the surprising tradeoff between ImageNet accuracy and perceptual similarity](https://arxiv.org/abs/2203.04946)
     - Perceptual score 와 image classification 성능간의 상관관계 분석 (from Google Research)
     - Perceptual loss를 위해서 VGG 많이 써왔음. 그러나 최신 모델들 (ResNet, EfficientNet, ViT 등) 의 Perceptual capability에 대한 연구는 별로 없었음
     - Perceptual: BAPPS 데이터, Image classification: ImageNet-1k
     - 놀랍게도 Image classification acc가 높아지면 perceptual score가 망가짐 (충분히 그럴 법도 한...)
![image](https://user-images.githubusercontent.com/11782739/158055402-6ff9b1e5-f272-438b-bbfb-cf35e7deee7a.png)
![image](https://user-images.githubusercontent.com/11782739/158055450-2d922561-d349-4075-808d-e85d5921d6ff.png)
![image](https://user-images.githubusercontent.com/11782739/158055472-82425edd-c593-46c2-82c8-f2f2f41422b8.png)
 
  - 흥미있는 연구
    - StyleNeRF (ICLR 2022) 코드공개: https://github.com/facebookresearch/StyleNeRF
    - [Model soups: averaging weights of multiple fine-tuned models improves accuracy without increasing inference time](http://arxiv.org/abs/2203.05482v1)
       - New SOTA of ImageNet-1k --> 이진원님
    - [On Embeddings for Numerical Features in Tabular Deep Learning](http://arxiv.org/abs/2203.05556v1) 
    - [An Empirical Study of Low Precision Quantization for TinyML](http://arxiv.org/abs/2203.05492v1)

**Comment by hollobit** [comment]
### 기계 학습으로 궤도 역학 재발견
- Paper: https://arxiv.org/abs/2202.02306
- Blog: https://astroautomata.com/paper/rediscovering-gravity/
>- 1600년대에 기계 학습이 있었다면 뉴턴이 만유인력의 법칙을 발견했을까 ?
>- NASA Horizon의 천문력 데이터를 기반으로 활용. 31개의 물체를 대상으로 훈련데이터 개발 
>- 1980년부터 2010년까지 30년 동안 30분 간격의 데이터를 훈련 데이터로, 2010~2013년 데이터를 검증 세트로 활용 
>- Graph Neural Network (GNN) based on the “Interaction Network” defined in [Battaglia et al., 2018](https://arxiv.org/abs/1806.01261)
>- 학습한 역학 규칙의 표현, symblolic expression의 정형화를 위해 symbolic regression와 evolutionary algorithm을 사용하는 [PySR 알고리즘](https://github.com/MilesCranmer/PySR) (Cranmer, 2022)을 사용
>- 마지막으로 질량 매개 변수를 고정된 기호 표현을 통해 GNN에 맞추는 방식 도입 

![x1](https://user-images.githubusercontent.com/998803/158040796-77eb0e5d-cf51-42e1-8e35-e3503c509891.png)
>- 데모 동영상: https://drive.google.com/file/d/1MLArRvQhZQFSG3vrg5MRuL8opZK-vU_a/view

### Freeform Body Motion Generation from Speech
- paper : https://arxiv.org/abs/2203.02291
- github : https://github.com/TheTempAccount/Co-Speech-Motion-Generation
>- 프레임워크는 두 부분으로 구성 : 음성 오디오에서 리듬 역학으로의 매핑을 학습하는 Rhythmic motion branch, 자유 형식 포즈 모드를 생성하기 위해 음성 텍스트의 의미 신호에 처리를 하는 CVAE로 구성된 Pose mode branch
>- Speech2Gesture 데이터셋과 TEDGesture 데이터셋, 그리고 일부 유튜브 비디오 데이터를 활용. 
>- 80% for training, 10% for testing, 10% for validation
>- SOTA 비교 : Audio to Body Dynamics (Audio2Body), Speech2Gesture (S2G) , Speech Drives Template (Tmpt), Trimodal-Context (TriCon), Mix-StAGE
>- Evaluation protocol은 세가지를 사용 : 1) 음성과 모션 간의 동기화(syncing), 2) 움직임의 다양성(diversity), 3) 실제와 비교한 움직임의 질(quality).  
>- 기타, 질적 비교 및 사용자 연구는 주관적인 평가로 포함됩니다.
<img width="1194" alt="스크린샷 2022-03-13 오전 10 38 48" src="https://user-images.githubusercontent.com/998803/158041137-abbc36a1-9cd2-40e7-ac39-b2c4ba88635c.png">

>- Video demo 
[![](https://res.cloudinary.com/marcomontalbano/image/upload/v1639640143/video_to_markdown/images/youtube--Wb5VYqKX_x0-c05b58ac6eb4c4700831b2b3070cd403.jpg)](https://youtu.be/Wb5VYqKX_x0 "")

**Comment by epicure** [comment]
Weekly AI ArXiv 만담 1주년 축하드립니다!

### 프롬프트에 의해 펼쳐지는 디퓨전 모델 활용기

**접할 수 있는 방법**

1. Github / Colab Notebook - [Disco Diffusion v5](https://colab.research.google.com/github/alembics/disco-diffusion/blob/main/Disco_Diffusion.ipynb) 
2. 배포된 모델 활용 Hugging Face [CLIP Guided Diffusion HQ](https://huggingface.co/spaces/EleutherAI/clip-guided-diffusion), Replicate [pyglide](https://replicate.com/afiaka87/pyglide) (추론 시간 30분 무료) 등
3. 디스코드 챗봇 [EleutherAI 디스코드](https://discord.gg/zBGx3azzUn)의 the-faraday-cage, [MidJourney](https://twitter.com/search?q=%40MidJourney) 등

이 중 엔드유저가 경험하기에 가장 문턱이 낮으며 빠르게 프롬프트 프로그래밍의 감을 잡을 수 있는 것은 챗봇을 통한 활용. 명령어와 프롬프트로 제어. 단, 코드로 접근할 수 없기 때문에 제어할 수 있는 것에는 한계가 있으며 그래서 오히려 프롬프트 프로그래밍에 집중하는 경향.

<img width="282" alt="image" src="https://user-images.githubusercontent.com/422362/158054972-31a83b17-a954-42d5-a9e1-85eb75c06c6f.png">
<img width="853" alt="image" src="https://user-images.githubusercontent.com/422362/158054991-2474f7b6-4100-46ba-a8d5-7d6526d24b4e.png">

프롬프트를 입력하면 확산과정을 보여주며, 결과를 이미지와 영상으로 다운로드 받을 수 있음.
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/422362/158055088-d444c529-b3d6-417d-aba1-625d5b9392dd.png">
또한 이 과정에서 다른 유저들이 어떤 프롬프트를 사용해서 어떤 결과를 얻는지 볼 수 있기 때문에 학습에도 유리. 디스코드 메시지 링크를 갈무리해서 다양한 예시 및 학습과정을 기록하는 등의 접근이 가능함.

**이미지 관련 태스크에서 챗봇의 약진 전망**

사용해 보면 사용할 수록 동시대 챗봇이 할 수 있는 태스크의 폭이 이미 넓어졌고, 더 넓어질 예정이라는 인상을 받음.

prompt: a dark soul boss, surreal oil painting → 4개의 중간 결과 중 업스케일 적용할 이미지를 선택 → 업스케일 및 다운로드 
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/422362/158056554-5c1857fc-a0d3-48a3-a9e6-ffd0c2c697be.png">

이 결과를 다시 <이미지 프롬프트>로 입력 가능, init image와는 다른 입력 이미지를 인코딩하는 해서 확산 방향을 조정하는 프롬프트로 활용

[GLIDE](https://paperswithcode.com/paper/glide-towards-photorealistic-image-generation), ([Weekly AI ArXiv 만담 - 35회차](https://github.com/jungwoo-ha/WeeklyArxivTalk/issues/35))의 DDIM 샘플링 보다 빠른 ICLR2022의 [PLMS](https://openreview.net/pdf?id=PlKWVd2yBkY) 샘플링을 쓰는 [Katherine Crowson](https://twitter.com/RiversHaveWings) 등의 작업이 빠르게 ML 창작자 커뮤니티에 번지고 있지만, 성능 문제 외에도 GLIDE에는 filtered dataset이 사용됐기 때문에(사람이 빠져있는) 창작자 커뮤니티에서는 12M의 text-image pair를 가지는 [fine-tuned cc12m_1](https://paperswithcode.com/paper/conceptual-12m-pushing-web-scale-image-text/review/) 에 머무르고 있는 경우가 있고 따라서 모델에 악용할 수 있는 바이어스가 있는 상황. (디스코드의 룰 등으로 원스트라이크 아웃의 강력한 제제를 하거나 필터를 걸지만)

**다국어를 활용했을 경우에 발견되는 편향**

프롬프트에 이모지를 흥미롭게 활용할 수 있는 것 처럼, 다국어를 쓰면 특정 유니코드 구간에서 편향이 발생함
<img width="779" alt="image" src="https://user-images.githubusercontent.com/422362/158057851-b9f2af21-d419-459a-b90c-fcd5d2188a83.png">

단, 창작자 커뮤니티는 더 많은 표현의 자유를 원하는 경향이 보이나, 대중에게 서비스할 때는 각별히 조심해야 할 부분. 관련해서 거대 언어 모델이 생성하는 글 못지 않은 영향이 있을 가능성.

**그 외의 아이디어 및 추측할 수 있는 경험에 기반한 기법**
...

**번외**

다크 소울 보스를 귀엽게 만들어 보기
prompt: a super cute dark soul boss, Calarts style, 🌈  외
<img width="507" alt="image" src="https://user-images.githubusercontent.com/422362/158058257-b9dca9b0-8fee-477e-a0f4-0084900effaa.png">

**함의**

낮아지는 문턱과 여전한 문턱이 상존, 프롬프트로 손쉽게 무엇인가를 생성할 수 있는 동시에 뭔가 새로운 것을 만들기 위해서는 예술의 기법, 작가명 등 배경지식을 아는 것과 서로 다른 영역을 점프해서 이어볼 수 있는 발상, 상상력이 필요. 단, 디스코드와 같은 커뮤니티 플랫폼이 이 간극을 메워 인간이 빠르게 학습할 수 있도록 돕는 동시에 그곳에 방대한 사용례와 프롬프트 사례가 수집이 되어 다시 서비스와 플랫폼을 개선할 에너지를 발생시킴.

**Comment by terryum** [comment]
### AI startups in the beauty industry

- 주제를 가져온 이유
   - 최근 뷰티AI 스타트업 쪽에 투자 소식이 많았음 : 룰루랩, 로켓뷰(찍검), CureSkin 등
   - 의료산업의 AI 도입 뿐만 아니라 뷰티 같은 전통산업의 AI이야기도 궁금해하실까 싶어서...
   - ART Lab 대표로서 뷰티 쪽에 AI연구자들이 관심을 가졌으면 하는 욕심도 있습니다 :)
   
- 뷰티시장 (2020년 기준)
   - 화장품 산업은 세계 500조 시장. 국내 50대 화장품기업 총매출 약 50조 (c.f. LG생활건강 8조, 아모레퍼시픽 5조 등) 
   - 이 중 스킨케어가 약 45%로 재구매도 높아 가장 매력적인 시장. 온라인거래는 약 12조/년으로 매년 큰 폭으로 성장 중

- AI in 뷰티시장
   - 온라인/디지털로 전환되는 시장에서의 화두는 '어떻게 온라인에서 더 나은 구매 경험을 제공할 것인가'임
   - 스킨케어 시장에선 '모바일 피부 진단'을 중심으로, 메이크업 시장에선 '가장 메이크업'을 중심으로 시장이 커지고 있음
   - 뷰티산업은 개인화가 매우 중요한 시장 -> AI가 활약할 부분이 많음
   
   
- 해외의 뷰티AI 스타트업   
   - [Perfect Corp](https://www.perfectcorp.com/ko) 
       - 2014년 대만에서 설립된 스타트업으로 작년 600억을 골드만삭스로부터 투자 받음
       - 가상 메이크업으로 시작해 최근 모바일 피부 진단으로 영역을 넓힘
       
       ![image](https://user-images.githubusercontent.com/12528769/158057898-a7085fc4-ede3-4526-9c53-5b07cd6b571d.png)

   - [CureSkin](https://cureskin.com/)
       - 2017년 인도에서 설립된 스타트업으로 일주일 전 60억 투자 완료
       - 피부진단 결과에 따라 맞춤형화장품을 배송
       
       ![image](https://user-images.githubusercontent.com/12528769/158059339-fd66dfab-6982-419d-973a-f12312cc9be5.png)

- 국내의 뷰티AI 스타트업
  - [로켓뷰(찍검)](http://www.rocketview.io/)
      - 2016년 설립된 스타트업으로 OCR 을 이용해 화장품 정보를 알려주는 스타트업
      - 2주 전 올리브영에 인수 됨 -> 화장품 추천AI 개발을 위한 올리브영의 전략 [[기사]](https://www.cosmorning.com/mobile/article.html?no=42444)
      
      ![image](https://user-images.githubusercontent.com/12528769/158058108-caf5f320-930e-49a2-afa6-42e513e99e2a.png)
  - [룰루랩](https://lulu-lab.com/)
      - 2017년 설립된 스타트업으로 피부진단 키오스크를 개발하여 피부진단 & 화장품 추천
      - 2주 전 SK쉴더스로부터 30억 투자 -> 비디면 리빙케어 /실버케어 산업 진출을 위한 전략 [[기사]](https://zdnet.co.kr/view/?no=20220302110119)
      
      ![image](https://user-images.githubusercontent.com/12528769/158058197-e9c4ce43-c9c4-4d4f-abfe-af2d831ef968.png)
  - [잼페이스](https://www.zamface.co.kr/)
     - 2018년 설립된 스타트업으로 뷰티유튜버의 영상을 보기 쉽게 해 줌.
     - 특히 activity recognition을 통해 특정 메이크업 순서로 바로 점프하게 해주는 기능이 핵심 AI기술
     - 작년 55억, 올해 45억 등 총 110억 누적 투자 유치 완료 [기사](https://platum.kr/archives/180962)
     
     ![image](https://user-images.githubusercontent.com/12528769/158059106-bdcb3224-b9ce-4702-a566-e166f8c05ccc.png)

  - [ART Lab](https://artlab.ai/)
     - 2019년 설립된 스타트업으로 모바일기반 피부진단과 화장품추천 AI를 집중 개발 중 
     - 뷰티산업의 딥마인드가 되겠다 : 최근 대기업들에 핵심 AI기술 공급 계약 체결 중 [[기사]](https://www.edaily.co.kr/news/read?newsId=01669526629143056&mediaCodeNo=257)
     - 2년전 네이버, 코스맥스로부터 시드 투자(8억), 올해 말엔...
     - 연구 하나하나가 novelty가 되는 노다지에서 함께 해요~ 티타임 ㄱㄱ  terry@artlab.ai 
     
     ![image](https://user-images.githubusercontent.com/12528769/158058810-f5491d53-0ac4-4ac4-bb08-3f38e37e1bf1.png)

**Comment by kimyoungdo0122** [comment]
- News
    - [AI-produced images can’t fix diversity issues in dermatology databases](https://www.theverge.com/2022/3/11/22971207/dermatology-ai-diversity-skin-tone-synthetic-images)
        - 테리님께서 관심을 갖지 않으실까 ㅎㅎ..
        - 생성된 이미지를 데이터셋으로 활용하는 것의 위험성
        - 피부과에서 피부암 및 피부 질환 진단에 필요한 이미지 데이터에 흑인의 피부 데이터가 많이 모자람
        - 자연스레 윤리 이슈로
        - 부족한 데이터를 생성으로 해결하는 것보다 제대로 수집하는 것이 중요하다는 골자의 뉴스 
    - [DeepMind claims its AI can decipher ancient Greek texts from damaged artifacts](https://venturebeat.com/2022/03/09/deepmind-claims-its-ai-can-decipher-ancient-greek-texts-from-damaged-artifacts/) 
        - 고대 그리스의 텍스트를 복원하는 AI를 딥마인드에서 연구!
        - 'Ithaca' 라는 프로젝트명의 이 고대 그리스 언어 복원 AI
        - 유적에 새겨져있는 고대 언어 텍스트가 손상된 부분을 복원하는데 사용할 수 있음
        - 전문가가 유적을 처음 보고 분석하여 복원하면 25%의 정확도를 보이지만, 분석가를 Ithaca가 보조하여 분석한다면 72%로 높은 성능을 보임
        - [Restoring and attributing ancient texts using deep neural networks](https://www.nature.com/articles/s41586-022-04448-z)
        - 78,608개의 고대 그리스 비문 데이터로 학습, 각 데이터에는 기록된 위치와 시기를 추정할 수 있는 메타 데이터가 있음
        - [[서울대 AI 연구원] 한국어 처리에서 언어학자의 역할(박진호 교수)](https://youtu.be/6PoA05AUllg)
        - AI가 다른 과학 및 공학 분야에 접목되어 새로운 지식의 발견에 기여하고 있고, 역사와 같은 인문학에도 기여를 할 수 있다는 점이 인상깊었습니다!
![image](https://user-images.githubusercontent.com/42539153/158062078-e61847ee-3050-4231-8909-ee398d15c4ae.png)

**Comment by hollobit** [comment]
### AI 및 국가 안보의 최근 개발: 알아야 할 사항
- https://www.lawfareblog.com/recent-developments-ai-and-national-security-what-you-need-know
>- AI가 군사 및 정보 우위를 주도하는 능력으로 인해 핵무기, 항공기, 컴퓨터 및 생명 공학과 대등한 변혁적인 국가 안보 기술이 될 잠재력을 갖고 있음 (Belfer Center 보고서) -  https://www.belfercenter.org/sites/default/files/files/publication/AI%20NatSec%20-%20final.pdf
>- 미 해군과 9개 파트너 국가는 80개의 공중, 수상 및 수중 무인 시스템을 포함하는 대규모 해군 훈련을 실시. 무인 시스템은 14개의 훈련 시나리오를 통해 선외 선원 구조 및 지역 모니터링과 같은 임무에 대한 유용성을 테스트 (2022.2.3) 
>- 국가가 국가 인공 지능 전략을 달성하기 위해 컴퓨팅 파워를 활용하는 방법 (브루킹스, 2022.1) - 한국을 선도국 그룹으로 분류https://www.brookings.edu/blog/techtank/2022/01/12/how-countries-are-leveraging-computing-power-to-achieve-their-national-artificial-intelligence-strategies/
<img src="https://i2.wp.com/www.brookings.edu/wp-content/uploads/2022/01/Formatted-Desouza-Fig1-whitebg.png?w=768&crop=0%2C0px%2C100%2C9999px&ssl=1">

>- [DARPA, F-16D 제트 전투기에 인공 지능(AI)을 장착하여 인간 파트너로서 AI에 대한 신뢰 강화](https://www.militaryaerospace.com/computers/article/14234351/artificial-intelligence-ai-dogfighting-trust) 
>- GAO(Government Accountability Office) [인공 지능: 무기 시스템의 개발 및 획득 기능 현황](https://www.gao.gov/assets/gao-22-104765.pdf) 보고서, 미 국방부는 2021년 4월 현재 최소 685개의 AI 프로젝트를 수행했고, 대부분의 국방 AI 기능이 지능 분석, 무인 무기 시스템 향상 및 전투 권장 사항 제공에 중점을 두고 있음을 발견
