### ISSUE TITLE
[20220327] Weekly AI ArXiv 만담 - 45회차 (Stanford AI Index Report 특집)

### ISSUE THREAD

**Issue by jungwoo-ha** [jungwoo-ha/WeeklyArxivTalk#45]
### [Stanford AI Index Report](https://hai.stanford.edu/research/ai-index-2022) ###
- [Ch.1: Research & Development](https://github.com/jungwoo-ha/WeeklyArxivTalk/issues/45#issuecomment-1079926676) (김영도님)
- [Ch.2: Technical Performance](https://github.com/jungwoo-ha/WeeklyArxivTalk/issues/45#issuecomment-1079922324) (이준형님)
- [Ch.3: Technical AI Ethics](https://github.com/jungwoo-ha/WeeklyArxivTalk/issues/45#issuecomment-1079893475) (이정현님)
- [Ch.4: The Economy and Education](https://github.com/jungwoo-ha/WeeklyArxivTalk/issues/45#issuecomment-1079874126) (이경훈님)
- [Ch.5: AI Policy and Governance](https://github.com/jungwoo-ha/WeeklyArxivTalk/issues/45#issuecomment-1079705198) (하정우님)

**Comment by jungwoo-ha** [comment]
### [AI Policy and Governance]
**요약**
- 25개국 AI법령이 2016년 1개 에서 2021년엔 18개로 증가. 
- 미국 연방정부의 경우 입법기록 기준으로 엄청 증가 했으나 실제 법제정으로 이어진 경우는 2%. 
![image](https://user-images.githubusercontent.com/11782739/160243514-326c27b9-f745-4501-874e-36d085ecd2c6.png)
- 그에 비해 주의회 입법은 20% 정도 (법령제안은 2012년 2개에서 2021년 131개까지 대폭 증가). 민주당이 공화당 2배
![image](https://user-images.githubusercontent.com/11782739/160243719-f83fe1e5-f408-4c66-bb3a-350277e78303.png)
- 각 주별로 편차가 꽤 큼. MA가 1등! 그런데 하와이는 왜이렇게 많은겨..
![image](https://user-images.githubusercontent.com/11782739/160243598-fa8b29c1-1a27-4e48-8bfb-1a2eec74fbd2.png)
- 117차 의회 회기(2021 ~ ): 295회 언급 vs. 116차 회기 (2019-2020): 506회 언급. 2017년부터 폭발적 증가
![image](https://user-images.githubusercontent.com/11782739/160243809-3329e14a-94a9-4b1a-9b90-010c0ef93628.png)
- 입법 정책 관련 활동은 스페인, 영국이 상당히 많음. 일본도 매우 많음. 한국은 법령은 적지 않은편인데 최근의 활동은 그닥
![image](https://user-images.githubusercontent.com/11782739/160243831-ff9b1627-f953-4cd1-9d22-09dc1c46e69d.png)
- 정책총서의 주제기준으로 규제관련이 좀 많아 보임 (프라이버스, 안전, 윤리 등등)
![image](https://user-images.githubusercontent.com/11782739/160243861-344e292b-db62-4ad7-bf2e-40d9610ad2db.png)

- 미국 연방정부의 공공 AI 투자 규모는 USD 1.67B (국방빼고), 국방분야는 USD 10B 정도이며 대부분은 DOD (국방성) 주도. 미국의 AI R&D의 중심축은 국방성이 컨트롤 타워로 보임 (생각보다 규모가 작아보여도 사실 미국은 기업중심으로 투자규모가 막강함)
![image](https://user-images.githubusercontent.com/11782739/160243883-94247efe-85d5-4346-a0b6-fde7030418e4.png)
![image](https://user-images.githubusercontent.com/11782739/160243896-e188445f-9ca0-4ccf-b951-33488d4ceaba.png)
![image](https://user-images.githubusercontent.com/11782739/160243910-0340e1ca-32ce-4599-807d-0435fe367781.png)

**Comment by ghlee0304** [comment]
![1](https://github.com/ghlee0304/Technical_Reposit/blob/master/AIReport2022_ch4_1.PNG?raw=true)
![2](https://github.com/ghlee0304/Technical_Reposit/blob/master/AIReport2022_ch4_2.PNG?raw=true)
![3](https://github.com/ghlee0304/Technical_Reposit/blob/master/AIReport2022_ch4_3.PNG?raw=true)
![4](https://github.com/ghlee0304/Technical_Reposit/blob/master/AIReport2022_ch4_4.PNG?raw=true)
![5](https://github.com/ghlee0304/Technical_Reposit/blob/master/AIReport2022_ch4_5.PNG?raw=true)
![6](https://github.com/ghlee0304/Technical_Reposit/blob/master/AIReport2022_ch4_6.PNG?raw=true)
![7](https://github.com/ghlee0304/Technical_Reposit/blob/master/AIReport2022_ch4_7.PNG?raw=true)
![8](https://github.com/ghlee0304/Technical_Reposit/blob/master/AIReport2022_ch4_8.PNG?raw=true)
![9](https://github.com/ghlee0304/Technical_Reposit/blob/master/AIReport2022_ch4_9.PNG?raw=true)
![10](https://github.com/ghlee0304/Technical_Reposit/blob/master/AIReport2022_ch4_10.PNG?raw=true)
![11](https://github.com/ghlee0304/Technical_Reposit/blob/master/AIReport2022_ch4_11.PNG?raw=true)
![12](https://github.com/ghlee0304/Technical_Reposit/blob/master/AIReport2022_ch4_12.PNG?raw=true)
![13](https://github.com/ghlee0304/Technical_Reposit/blob/master/AIReport2022_ch4_13.PNG?raw=true)
![14](https://github.com/ghlee0304/Technical_Reposit/blob/master/AIReport2022_ch4_14.PNG?raw=true)
![15](https://github.com/ghlee0304/Technical_Reposit/blob/master/AIReport2022_ch4_15.PNG?raw=true)
![16](https://github.com/ghlee0304/Technical_Reposit/blob/master/AIReport2022_ch4_16.PNG?raw=true)

**Comment by nick-jhlee** [comment]
# Chapter 3. Technical AI Ethics

## Highlights
- NLP 모델들은 커지는 만큼 bias도 (유래없이) 커짐..
  - 170M ==> 280B하면서 29% increase in bias
- Multimodal 모델들에는 bias도 multimodal 형식으로 나타내짐
  - CLIP에선, 흑인들의 이미지가 다른 인종의 이미지보다 **2배 가까이** nonhuman으로 misclassify가 됨
- AI ethics에 관련된 논문들이 대단히 쏟아지고 있고, **academic한 분야에서 많은 implication이 있는 mainstream으로 바뀜**
  - 특히 industry affiliation가 있는 publication이 71% 증가함
  
## 3.1 Meta-analysis of fairness and bias metrics

## 3.2 Natural Language Processing Bias Metrics

## 3.3 AI Ethics trends at FACCT and NeurIPS

## 3.4 Factuality and Turthfulness

**Comment by hollobit** [comment]
### Stanford AI Index로부터 무엇을 얻을 수 있을까 ?

<img width="1085" alt="스크린샷 2022-03-27 오후 9 17 06" src="https://user-images.githubusercontent.com/998803/160281012-d9b0a056-e253-42de-aa5b-772b1a9949d7.png">

**Comment by veritas9872** [comment]
Chapter 2. Technical Performance

A scorecard across many different fields of deep learning.

생각한 것보다 성적표를 읽는 것 같아 분야별로 묶는 대신 성적 순서대로 묶었습니다. ㅋㅋㅋㅋ


O: Outstanding.

1. Facial Recognition.
2. 


E: Exceeds Expectations.

1. 

A: Acceptable.

1.

**Comment by kimyoungdo0122** [comment]
### Ch.1: Research & Development

- AI분야 연구는 다른 STEM(Science, Technology, Engineering, Mathmatics) 분야에 비해 Git이나 arxiv 등 오픈 소스로 공개하는 경향이 큰 차이점
- publication은 매년 늘고 있는 추세, 21년(334,497건)에는 10년(162,444건)에 비해 2배 이상 늘었습니다.
![image](https://user-images.githubusercontent.com/42539153/160281604-cba874a5-1f71-4293-83df-76a95c92e336.png)

- 그리고 51.5%, 절반 이상이 저널에 게재되었으며, 21.5%가 컨퍼런스에, 17% repository에 게재되었습니다.
![image](https://user-images.githubusercontent.com/42539153/160281776-00f087a8-d503-432c-8c7f-2018dec8eea3.png)

- 패턴 인식, 머신러닝 분야의 출간 수는 증가했으나 관련 분야의 연구는 약간 증가하는 추세
![image](https://user-images.githubusercontent.com/42539153/160281948-91d0ece0-1755-45a7-bb01-aa5f729a3911.png)

- 미국과 중국이 AI 연구에서도 경쟁하고 있지만, 동시에 협력 연구도 많이 진행하고 있으며 미국 연구자 중국 연구자가 함께 출간한 경우도 전체 AI 연구의 10%에 달한다
![image](https://user-images.githubusercontent.com/42539153/160282036-c7711c48-65af-4b39-bbe0-39cad7f61ad9.png)

- 흥미롭게도, 미국과 중국의 공동 연구가 1등이고 미국과 영국의 연구가 2등인데 3등이 중국과 오스트레일리아로 나타남. 대부분 미국과 다른 국가간 협력 연구의 사례가 많음
![image](https://user-images.githubusercontent.com/42539153/160282084-4dbd4fe4-c2a3-4191-941c-1c14716742e9.png)

- 저널에 게재된 연구의 수가 폭발적으로 증가했다는 소식은 이제는 익숙하시죠?
![image](https://user-images.githubusercontent.com/42539153/160282186-4710db05-0dc7-4fd7-9e9b-c93d7896ba6d.png)

- 중국이 저널 논문 게재도 많이 하는데, 인용 수도 많이 늘었다. 단순히 양적인 공세가 아니라 연구적으로 인정받는 부분도 많이 늘었다는 의미일지?
![image](https://user-images.githubusercontent.com/42539153/160282260-1508179c-e290-41da-96e0-c12bd34e4fcb.png)

- 그런데 컨퍼런스는 또 달라요.
![image](https://user-images.githubusercontent.com/42539153/160282324-eb4fac33-e35e-4072-a095-caabe8538519.png)

- 컨퍼런스에서는 미국 연구의 인용이 높고 중국 연구의 인용이 낮습니다. 저널과 컨퍼런스는 어떤 차이가 있을까요?
![image](https://user-images.githubusercontent.com/42539153/160282355-c0a4062d-f16b-44f5-a396-6ecc24a47285.png)

- Git repository는 중요한 연구 공개 장소
![image](https://user-images.githubusercontent.com/42539153/160282388-63ba25d2-ac74-42d7-98e7-542c4821f639.png)

- 연구에 그치지 않고 특허로 이어지는 경우가 폭발적으로 늘었습니다.
![image](https://user-images.githubusercontent.com/42539153/160282425-50c67f44-8b8a-495f-bce6-cae9fbeb3610.png)

- 특히 중국이 특허를 출원 및 허가하는 경우가 많고, 미국과 영국은 상대적으로 조심스럽게 허가하는 모습입니다.
![image](https://user-images.githubusercontent.com/42539153/160282490-6a4e5da8-4ee8-4868-90d6-92021b21b273.png)

- 구현 관련된 부분도 중요하죠? 많은 사례에서 pytorch가 tensorflow를 연구 부문에서 앞섰다는 소식을 접하셨을테지만, 별을 4만 개 이상 받은 경우 중에서는 여전히 tensorflow가 많은 경우를 보이고 있습니다.
![image](https://user-images.githubusercontent.com/42539153/160282573-ee04e282-d758-479f-a1e9-8d927f299eb4.png)
